"""Lawyer Prep Brief generator.

Compiles accumulated 'unclear' items and suggested lawyer questions
from Q&A and scenario analysis sessions into an exportable markdown document.

This creates an actionable briefing document the user can bring to
their lawyer, containing specific questions grounded in the contract.
"""

import logging
from datetime import datetime, timezone
from backend.models.schemas import DocumentSession, Clause

logger = logging.getLogger(__name__)


def generate_brief(session: DocumentSession) -> str:
    """Generate a Lawyer Prep Brief as markdown.
    
    Compiles:
    - Document summary (type, clause count, categories)
    - Accumulated unclear items from Q&A/scenario sessions
    - Suggested lawyer questions
    - Key clauses that need attention
    
    Returns:
        Markdown-formatted briefing document
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    doc_type_display = session.doc_type.value.replace("_", " ").title() if session.doc_type else "Unknown"
    
    # Group clauses by category for summary
    categories: dict[str, list[Clause]] = {}
    for clause in session.clauses:
        cat = clause.category.value if clause.category else "general"
        categories.setdefault(cat, []).append(clause)
    
    brief = f"""# Lawyer Prep Brief

**Generated by ClauseGuard** | {now}

> **Important:** This document is generated by an AI assistant to help you
> prepare for a legal consultation. It is NOT legal advice. Please review
> all items with a qualified legal professional.

---

## Document Overview

- **Document Type:** {doc_type_display}
- **Original File:** {session.filename}
- **Total Clauses Identified:** {len(session.clauses)}
- **Categories Covered:** {', '.join(cat.replace('_', ' ').title() for cat in sorted(categories.keys()))}

---

## Questions for Your Lawyer

The following questions were generated during your review of the document.
Each question is based on specific clauses or scenarios that were unclear
or require professional interpretation.

"""
    
    if session.lawyer_questions:
        for i, question in enumerate(session.lawyer_questions, 1):
            brief += f"{i}. {question}\n\n"
    else:
        brief += "*No specific lawyer questions were generated during this session.*\n\n"
    
    brief += """---

## Items Requiring Clarification

The following items were flagged as unclear or not fully established
in the document during your review.

"""
    
    if session.unclear_items:
        for i, item in enumerate(session.unclear_items, 1):
            brief += f"{i}. {item}\n\n"
    else:
        brief += "*No unclear items were flagged during this session.*\n\n"
    
    brief += """---

## Document Structure Summary

"""
    
    for cat_name in sorted(categories.keys()):
        cat_clauses = categories[cat_name]
        display_name = cat_name.replace('_', ' ').title()
        brief += f"### {display_name} ({len(cat_clauses)} clause{'s' if len(cat_clauses) != 1 else ''})\n\n"
        for clause in cat_clauses:
            brief += f"- **{clause.section}** (Page {clause.page}, {clause.id})\n"
        brief += "\n"
    
    brief += """---

## Next Steps

1. Review the questions above with your lawyer
2. Bring this document and the original contract to your consultation
3. Ask your lawyer to explain any clauses you're still unsure about
4. Request specific modifications for any clauses your lawyer identifies as concerning

---

*Generated by ClauseGuard — AI-powered contract analysis for informed legal consultations.*
"""
    
    logger.info(f"Generated brief with {len(session.lawyer_questions)} questions and {len(session.unclear_items)} unclear items")
    return brief
